app/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from app import views



app_name = 'app'

urlpatterns = [

    path('', TemplateView.as_view(
        template_name='index.html', 
        extra_context={'title':'Index Title', 'content':'Index body'}),
        name='index'),

    path('other/', views.OtherView.as_view(), name='other'),

    path('redirect/', RedirectView.as_view(url='https://muller.nocciolli.com.br/'), name='go-to-muller'),

    path('other2/<int:pk>', views.PostTaskView.as_view(), name='posttask'),

    path('other3/<int:pk>', views.TaskView.as_view(), name='singletask'),

]

books/urls.py
from django.urls import path
from books import views



app_name = 'books'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('<slug:slug>/', views.BookDetailView.as_view(), name='book-detail'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('app.urls')),
    
    path('books/', include('books.urls')),
    
]

app/models.py
from django.db import models



class BaseTest(models.Model):

    name = models.CharField(max_length=100)
    count = models.IntegerField(default=0)

books/models.py
from django.db import models



class Books(models.Model):

    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0)

app/views.py
# REQUIREMENTS
from django.views.generic.base import TemplateView, RedirectView
from django.shortcuts import get_object_or_404
from django.db.models import F
from typing import Any
# MODELS
from app.models import BaseTest



class OtherView(TemplateView):

    template_name = 'otherpage.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:

        context = super().get_context_data(**kwargs)

        context['basetest'] = BaseTest.objects.get(id=1)
        context['title'] = 'Other Page Title'

        return context
    


class PostTaskView(RedirectView):

    pattern_name = 'app:singletask'

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:

       test = BaseTest.objects.filter(pk=kwargs['pk'])
       test.update(count = F('count') + 1)

       return super().get_redirect_url(*args, **kwargs)



class TaskView(TemplateView):

    template_name = 'otherpage3.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:

        context = super().get_context_data(**kwargs)
        
        context['test'] = get_object_or_404(BaseTest, pk=self.kwargs.get('pk'))
        context['title'] = 'Other Page Title (After Redirect)'

        return context

books/views.py
# REQUIREMENTS
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.db.models import F
from typing import Any
# MODELS
from books.models import Books



class IndexView(TemplateView):

    template_name = 'home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context = super().get_context_data(**kwargs)
        
        context['books'] = Books.objects.all()
        context['title'] = 'Books Page'

        return context
    
    

class BookDetailView(DetailView):

    model = Books
    template_name = 'detailbook.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:

        context = super().get_context_data(**kwargs)

        post = Books.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count = F('count') + 1)

        return context

app/templates/index.html
<html>

    <head>
        <title>{{ title }}</title>
    </head>

    <body>
        <h1>{{ content }}</h1>
        <p><a href='{% url 'app:other' %}'>Go to other page >></a></p>
    </body>
    
</html>

app/templates/otherpage.html
<html>

    <head>
        <title>{{ title }}</title>
    </head>

    <body>
        <h1>Other Page</h1>
        <p>Database:</p>
        <p>ID: {{ basetest.id }}</p>
        <p>NAME: {{ basetest.name }}</p>
        <p>REDIRECT COUNT: {{ basetest.count }}</p>
        <br/>
        <p><a href='{% url 'app:index' %}'>Go to index page <<</a></p>
        <p><a href='{% url 'books:index' %}'>Go to books page >></a></p>
        <p><a href='{% url 'app:posttask' pk=basetest.id %}'>Go to task redirect page >></a></p>
    </body>
    
</html>

app/templates/otherpage3.html
<html>

    <head>
        <title>{{ title }}</title>
    </head>

    <body>
        <h1>Other Page (After redirect)</h1>
        <p>Database:</p>
        <p>ID: {{ test.id }}</p>
        <p>NAME: {{ test.name }}</p>
        <p>REDIRECT COUNT: {{ test.count }}</p>
        <br/>
        <p><a href='{% url 'app:index' %}'>Go to index page <<</a></p>
        <p><a href='{% url 'app:other' %}'>Go to other page <<</a></p>
        <p><a href='{% url 'books:index' %}'>Go to books page >></a></p>
        <p><a href='{% url 'app:go-to-muller' %}' target='_blanc'>Go to Müller Nocciolli page >></a></p>
    </body>
    
</html>

books/templates/detailbook.html
<html>

    <head>
        <title>Livro "{{ book.title }}"</title>
    </head>

    <body>
        <h1>Livro:</h1>
        <br/>
        <p>ID: {{ book.id }}</p>
        <p>TITLE: {{ book.title }}</p>
        <p>AUTHOR: {{ book.author }}</p>
        <p>GENRE: {{ book.genre }}</p>
        <p>ISBN: {{ book.isbn }}</p>
        <p>COUNTER: {{ book.count }}</p>
        <br/>
        <p><a href='{% url 'app:index' %}'>Go to index page <<</a></p>
        <p><a href='{% url 'app:other' %}'>Go to other page <<</a></p>
        <p><a href='{% url 'books:index' %}'>Go to books page <<</a></p>
        <p><a href='{% url 'app:go-to-muller' %}' target='_blanc'>Go to Müller Nocciolli page >></a></p>
    </body>
    
    </html>

books/templates/home.html
<html>

    <head>
        <title>{{ title }}</title>
        <style>
            .table{
                font-family: Arial;
                text-align: left;
            }
            .table th{
                background-color:#333;
                color:#fff;
                padding:10px;
            }
            .table td{
                background-color:#f4f4f4;
                color:#333;
                padding:10px;
            }
        </style>
    </head>

    <body>
        <h1>Books Page</h1>
        <p></p>
        <div>
            <table class="table" style="width:958px;">
                <thead>
                  <tr>
                    <th scope="col" style="">#</th>
                    <th scope="col" style="background-color:#333; color:#fff; padding:10px;">Title</th>
                    <th scope="col" style="background-color:#333; color:#fff; padding:10px;">Author</th>
                    <th scope="col" style="background-color:#333; color:#fff; padding:10px;">Genre</th>
                    <th scope="col" style="background-color:#333; color:#fff; padding:10px;">Code</th>
                    <th scope="col" style="background-color:#333; color:#fff; padding:10px;">Action</th>
                  </tr>
                </thead>
                <tbody>
                {% for book in books %}
                  <tr>
                    <th scope="row" style="background-color:#f4f4f4; color:#333; padding:10px;">{{ book.id }}</th>
                    <td style="background-color:#f4f4f4; color:#333; padding:10px;">{{ book.title }}</td>
                    <td style="background-color:#f4f4f4; color:#333; padding:10px;">{{ book.author }}</td>
                    <td style="background-color:#f4f4f4; color:#333; padding:10px;">{{ book.genre }}</td>
                    <td style="background-color:#f4f4f4; color:#333; padding:10px;">{{ book.isbn }}</td>
                    <td style="background-color:#f4f4f4; color:#333; padding:10px;">
                        <a href="{% url 'books:book-detail' slug=book.slug %}"><button type="button">Show Book</button></a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              <br/>
              <p><a href='{% url 'app:index' %}'>Go to index page <<</a></p>
              <p><a href='{% url 'app:other' %}'>Go to other page <<</a></p>
              <p><a href='{% url 'app:go-to-muller' %}' target='_blanc'>Go to Müller Nocciolli page >></a></p>
        </div>
    </body>
    
</html>